In [1]:
# Numpy - 고성능 과학 계산, 배열연산 배열 생성

#  ㄴ 숫자
# 배열이란?????????
# 리스트 - 다양한 자료형을 나열 자료형, 인덱스로 접근

# 배열 - 하나의 자료형을 나열하는 자료형, 인덱스로 접근 (int, float, str)

In [2]:
# numpy 사용 방법
import numpy as np

In [3]:
# 1차원 배열 생성하기

# 배열 == array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
list1 = [10,20,30,40,50]
arr2 = np.array(list1)
arr2

array([10, 20, 30, 40, 50])

In [5]:
# 2차원 배열 생성
arr3 = np.array([[1,2,3], [10,20,30]])
arr3

array([[ 1,  2,  3],
       [10, 20, 30]])

In [6]:
# 배열의 속성을 확인해봅시다!

# 1. 배열의 크기 - 다차원배열의 크기를 알아내는데 유용
#               ㄴ 배열명.shape

# 튜플로 return이 됨
arr3.shape # 행, 열로 출력

# 행만 출력
print(arr3.shape[0])

# 열만 출력
print(arr3.shape[1])

2
3


In [7]:
# 2. 차원수 - 해당 배열이 몇 차원이 알려주는 속성
#           ㄴ 배열명.ndim
print(arr2.ndim)
print(arr3.ndim)

1
2


In [8]:
# 3. 전체 요소개수 - 해당 배열의 값들의 수를 알려주는 속성
#                  ㄴ .size
print(arr2.size)
print(arr3.size)

5
6


In [9]:
# 4. 데이터 타입 - 요소의 타입을 알려주는 솟ㄱ성
#                 ㄴ .dtype

In [10]:
# 배열 함수들 알아보기

In [11]:
# 1. 0으로 초기화 하는 함수
# .zeros((행,열))
arr_zero

NameError: name 'arr_zero' is not defined

In [12]:
# 2. 1로 초기화 하는 함수
# .ones((행, 열))
arr_one = np.ones((3,4))
arr_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# 3. 그 외 수로 초기화 하는 함수
# .full((행, 열), 초기화 할 값)
arr_full = np.full((3,4), 7)
arr_full

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [14]:
# 4. 연속 값으로 초기화 하는 함수 - 1차원 배열
# .arange(시작 값, 끝 값) - 끝 값은 미만
arr_arange = np.arange(1, 51)
arr_arange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [15]:
# 4. 1 연속 값으로 초기화 하는 함수 - step이 있기!
arr_arange2 = np.arange(1,51, 10)
arr_arange2

array([ 1, 11, 21, 31, 41])

In [16]:
list2 = []
for i in range(1,51):
    list2.append(i)
print(list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


## numpy 인덱싱, 슬라이싱 - 데이터 접근 및 처리

In [17]:
# 1차원 배열 만들기
arr4 = np.array([10,20,30,40,50,60])
arr4

array([10, 20, 30, 40, 50, 60])

In [18]:
# 인덱싱
# 리스트의 인덱싱 - list명[인덱스 숫자]
# 넘파이의 배열도 동일
# 인덱싱 방법 --> []

print(arr4[3])

# 한번에 여러요소를 접근하는 경우 대괄호 한번 더 씌워주기
print(arr4[[0,4]])

40
[10 50]


#### 1차원 슬라이싱

In [19]:
# 리스트 슬라이싱 - [:]
# 배열도 동일
print(arr4[1:5])
print(arr4[:5])
print(arr4[2:])
print(arr4[:])

[20 30 40 50]
[10 20 30 40 50]
[30 40 50 60]
[10 20 30 40 50 60]


### 2차원 인덱싱

In [20]:
# 1차원 배열을 2차원 배열로 만들어주는 함수
# .reshape(행, 열)
arr5 = arr4.reshape(2,3)
arr5

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
print(arr5[0]) # 10, 20, 30
print(arr5[0][1])

# 2차원 배열 데이터 접근 하는 방법 1가지 더 존재
# [행, 열] - ,(comma) 기준 앞이 행 뒤가 열
print(arr5[0,1])

[10 20 30]
20
20


##### 2차원 슬라이싱

In [22]:
arr5[0,:] # , 기준 앞은 행 뒤는 열
# 행은 0번째 (인덱싱), 열은 슬라이싱으로 전부 출력

array([10, 20, 30])

In [23]:
# 20, 30만 출력하고 싶다!
print(arr5[0,1:])

# 40, 50만 출력하고 싶다
print(arr5[1,:2])

# 10, 20, 40, 50
print(arr5[0:2, 0:2])

[20 30]
[40 50]
[[10 20]
 [40 50]]


In [24]:
arr5[:,[0,2]]

array([[10, 30],
       [40, 60]])

In [25]:
arr5[:,::2] # [:,::step] step작성

array([[10, 30],
       [40, 60]])

In [26]:
# 데이터 수정
# 수정하고 싶은 위치 접근 후 대입 -- 인덱싱(슬라이싱) 한 후 = 원하는 변수
# arr5의 0행에 있는 데이터를 모두 100으로 수정
arr5[0] = 100
# arr5[0] == arr5[0,:]
print(arr5)

arr5[0,:] = [10,20,30]
print(arr5)

[[100 100 100]
 [ 40  50  60]]
[[10 20 30]
 [40 50 60]]


In [27]:
# 데이터 추가
# list의 경우 append와 insert
# append(추가할 array, 추가 할 값) - 맨끝에 추가
arr6 = np.append(arr5, 30)
arr6

array([10, 20, 30, 40, 50, 60, 30])

In [28]:
# 데이터 병합
# concatenate ([합할 배열])
list1 = [1,2,3,4,5]
list2 = [10,20,30,40,50]
print(list1 + list2) # 리스트의 경우 더할 시 데이터가 병합의 느낌

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


In [29]:
arr7 = np.array([1,2,3,4,5])
arr8 = np.array([10,20,30,40,50])

arr_concat = np.concatenate([arr7, arr8])
arr_concat

array([ 1,  2,  3,  4,  5, 10, 20, 30, 40, 50])

### 조건에 맞는 데이터 접근하기

##### 불리언 인덱싱

In [30]:
bool_arr = [True, False]

# numpy에 있는 random함수
np.random.seed(1) #
bool_arr1 = np.random.choice(bool_arr, size = 10)
# True, False 의 값을 랜덤으로 10개 만들겠습니다
print(bool_arr1)

temp_arr = np.arange(10)
print(temp_arr)

# temp_arr 불리언 인덱싱
# 불리언 인덱싱 - True인 값들 만 출력
# 불리언 인덱싱 - True, False가 담긴 array를 인덱싱
temp_arr[bool_arr1]

[False False  True  True False False False False False  True]
[0 1 2 3 4 5 6 7 8 9]


array([2, 3, 9])

In [31]:
# 작성한 조건으로 불리언 인덱싱

# 성적데이터를 랜덤으로 생성
np.random.seed(7)
score_arr = np.random.randint(50, 100, size = 20)
display(score_arr)
student_arr = np.arange(1, 21)
display(student_arr)

array([97, 54, 75, 53, 69, 73, 89, 78, 64, 73, 58, 75, 96, 92, 76, 58, 89,
       88, 54, 98])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
# 논리연산자 사용해서 80점 이상인 학생들만 출력
# <, >, ==, and, or, not, in
score_arr[score_arr > 80]

array([97, 89, 96, 92, 89, 88, 98])

In [33]:
score_arr[score_arr > 80].size

7

In [34]:
# 성적이 60점 이상인 학생들을 출력
student_arr[score_arr >= 60]

array([ 1,  3,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 17, 18, 20])

## 배열의 연산

In [35]:
arr10 = np.array([1,2,3,4,5])
display(arr10)

# 연산
arr10 = arr10 + 10
display(arr10)

array([1, 2, 3, 4, 5])

array([11, 12, 13, 14, 15])

In [36]:
arr11 = np.array([1,2,3,4,5])
arr12 = np.array([10,20,30,40,50])

display(arr11 + arr12)

array([11, 22, 33, 44, 55])

In [46]:
# 파일 불러오기 # 경로 잘 찾아가기
# delimiter = '구분자'
height_weight_data = np.loadtxt('data/height_weight.txt', delimiter=',')
data = height_weight_data

In [39]:
# 데이터의 정보 확인
print(height_weight_data.shape) # 2. 10데이터 (0행 - 키, 1행 - 몸무게)

print(height_weight_data.ndim)

(2, 10)
2


In [52]:
height = data[0]
weight = data[1]


bmi = (weight / (height/100 * height/100))
bmi

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [58]:
bool = (bmi > 23)
bmi[bool]

array([27.07018468, 25.86122449, 24.20652885, 23.14392095, 23.62028791,
       25.59220998])